### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by ibakayoko** [palantirnet/federated-search-demo#26]
[vagrant@federated-search-demo:/var/www/federated-search-demo.local$ phing build install-all
Buildfile: /var/www/federated-search-demo.local/build.xml
 [property] Loading /var/www/federated-search-demo.local/conf/build.vagrant.properties
 [property] Unable to find property file: /var/www/federated-search-demo.local/conf/build.vagrant.properties... skipped
 [property] Loading /var/www/federated-search-demo.local/conf/build.default.properties

federated-search-demo > build:

 [property] Loading /var/www/federated-search-demo.local/conf/build.d8.properties
 [property] Loading /var/www/federated-search-demo.local/conf/build.default.properties

federated-search-demo > drupal-build:

federated-search-demo > drupal-prepare-filesystem:

federated-search-demo > create-placeholder:

     [echo] web/d8/docroot/modules/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d8/docroot/themes/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d8/docroot/profiles/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d8/docroot/sites/default already exists.
    [chmod] Changed file mode on '/var/www/federated-search-demo.local/web/d8/docroot/sites/default' to 750

federated-search-demo > drupal-prepare-settings:

     [copy] Copying 1 file to /var/www/federated-search-demo.local/web/d8/docroot/sites/default

federated-search-demo > drupal-prepare-services:

     [copy] Copying 1 file to /var/www/federated-search-demo.local/web/d8/docroot/sites/default
 [property] Loading /var/www/federated-search-demo.local/conf/build.d7.properties
 [property] Loading /var/www/federated-search-demo.local/conf/build.default.properties

federated-search-demo > drupal-build:

federated-search-demo > drupal-prepare-filesystem:

federated-search-demo > create-placeholder:

     [echo] web/d7/docroot/modules/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d7/docroot/themes/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d7/docroot/profiles/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d7/docroot/sites/default already exists.
    [chmod] Changed file mode on '/var/www/federated-search-demo.local/web/d7/docroot/sites/default' to 750

federated-search-demo > drupal-prepare-settings:

     [copy] Copying 1 file to /var/www/federated-search-demo.local/web/d7/docroot/sites/default

federated-search-demo > drupal-prepare-services:

     [copy] Copying 1 file to /var/www/federated-search-demo.local/web/d7/docroot/sites/default
 [property] Loading /var/www/federated-search-demo.local/conf/build.d8-domain.properties
 [property] Loading /var/www/federated-search-demo.local/conf/build.default.properties

federated-search-demo > drupal-build:

federated-search-demo > drupal-prepare-filesystem:

federated-search-demo > create-placeholder:

     [echo] web/d8-domain/docroot/modules/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d8-domain/docroot/themes/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d8-domain/docroot/profiles/custom already exists.

federated-search-demo > create-placeholder:

     [echo] web/d8-domain/docroot/sites/default already exists.
    [chmod] Changed file mode on '/var/www/federated-search-demo.local/web/d8-domain/docroot/sites/default' to 750

federated-search-demo > drupal-prepare-settings:

     [copy] Copying 1 file to /var/www/federated-search-demo.local/web/d8-domain/docroot/sites/default

federated-search-demo > drupal-prepare-services:

     [copy] Copying 1 file to /var/www/federated-search-demo.local/web/d8-domain/docroot/sites/default

federated-search-demo > install-all:

federated-search-demo > install-d8:

 [property] Loading /var/www/federated-search-demo.local/conf/build.d8.properties
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

federated-search-demo > install-drupal-at-root:

federated-search-demo > validate-clean-conf:

    [chmod] Changed file mode on '/var/www/federated-search-demo.local/web/d8/docroot/sites/default' to 777
    [chmod] Changed file mode on '/var/www/federated-search-demo.local/web/d8/docroot/sites/default/settings.php' to 777
   [delete] Directory /var/www/federated-search-demo.local/web/d8/docroot/sites/default/files cannot be removed using the file attribute. Use dir instead.
   [delete] Deleting directory /var/www/federated-search-demo.local/web/d8/docroot/sites/default/files
    [mkdir] Created dir: /var/www/federated-search-demo.local/web/d8/docroot/sites/default/files
    [drush] Executing '/var/www/federated-search-demo.local/vendor/bin/drush --site-name="FS Demo D8" --account-name="admin" --account-pass="admin" --nocolor --root="/var/www/federated-search-demo.local/web/d8/docroot" --uri="http://fs-demo.d8.local" --config="/var/www/federated-search-demo.local/conf/drushrc.php" --yes site-install "config_installer"'...
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                        [ok]
Drupal\Core\Installer\Exception\AlreadyInstalledException: <ul>                                                                                                                                  [error]
<li>To start over, you must empty your existing database and copy <em>default.settings.php</em> over <em>settings.php</em>.</li>
<li>To upgrade an existing installation, proceed to the <a href="/update.php">update script</a>.</li>
<li>View your <a href="http://fs-demo.d8.local">existing site</a>.</li>
</ul> in /var/www/federated-search-demo.local/web/d8/docroot/core/includes/install.core.inc:536
Stack trace:
#0 /var/www/federated-search-demo.local/web/d8/docroot/core/includes/install.core.inc(122): install_begin_request(Object(Composer\Autoload\ClassLoader), Array)
#1 /var/www/federated-search-demo.local/vendor/drush/drush/includes/drush.inc(727): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#2 /var/www/federated-search-demo.local/vendor/drush/drush/includes/drush.inc(712): drush_call_user_func_array('install_drupal', Array)
#3 /var/www/federated-search-demo.local/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#4 /var/www/federated-search-demo.local/vendor/drush/drush/commands/core/site_install.drush.inc(271): drush_core_site_install_version('config_installe...', Array)
#5 /var/www/federated-search-demo.local/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('config_installe...')
#6 /var/www/federated-search-demo.local/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#7 /var/www/federated-search-demo.local/vendor/drush/drush/includes/command.inc(199): drush_command('config_installe...')
#8 /var/www/federated-search-demo.local/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#9 /var/www/federated-search-demo.local/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 /var/www/federated-search-demo.local/vendor/drush/drush/drush.php(12): drush_main()
#11 {main}
    [drush] You are about to DROP all tables in your 'fs-demo-d8' database. Do you want to continue? (y/n): y
[phingcall] /var/www/federated-search-demo.local/build.xml:69:106: Drush exited with code 1
[phingcall] /var/www/federated-search-demo.local/build.xml:101:52: Execution of the target buildfile failed. Aborting.

BUILD FAILED
/var/www/federated-search-demo.local/build.xml:173:39: Execution of the target buildfile failed. Aborting.

Total time: 2.3844 seconds

vagrant@federated-search-demo:/var/www/federated-search-demo.local$

**Comment by ibakayoko** [comment]
My bad.
Was able to install.

 [drush] Import the listed configuration changes? (y/n): y
    [drush] Executing '/var/www/federated-search-demo.local/vendor/bin/drush --nocolor --root="/var/www/federated-search-demo.local/web/d8-domain/docroot" --uri="http://fs-demo.d8-1.local" --config="/var/www/federated-search-demo.local/conf/drushrc.php" php-eval "'node_access_rebuild\(\)\;'"'...

BUILD FINISHED

Total time: 2 minutes  49.63 seconds
